New navbar
DteTRPod3/TRPod3_XtremeCars pull request #14
Opened 2022-05-17 10:21 UTC by Pratishah

![image](https://user-images.githubusercontent.com/96569364/168789670-b1a0022d-b4a0-424b-9388-adef9cc4130f.png)

added styling for Navbar and  counter on wishlist and cart icons

2022-05-17 15:17 UTC, pashedin commented
In the screenshots I see the 0 item count shows up, when 0 pleas display nothing. ALso, when the count is added highlight the count, as if pill.

2022-05-17 15:28 UTC, pashedin requested changes

2022-05-17 15:28 UTC, pashedin commented on src/components/Navbar/Navbar.scss
> +.nav-bar--car-btn-group {
Please read the BEM document again. 
it should be `block__element--modifier`

2022-05-17 15:28 UTC, pashedin commented on src/components/Navbar/Navbar.tsx
>          </div>
This is your `nav-cart-container` block

2022-05-17 15:28 UTC, pashedin commented on src/components/Navbar/Navbar.tsx
> +            <img className="nav-bar-wish-icon" src={wishlist} alt="wishlist" />
this for e.g is your element 
hence an appropriate name would be `nav-cart-contianer__icon`

2022-05-17 15:28 UTC, pashedin commented on src/components/Navbar/Navbar.tsx
> +            <img className="nav-bar-wish-icon" src={wishlist} alt="wishlist" />
Now lets say if we want to for some reason programattically switch between having this wichlist image with and without borders, we would  create 2 seperate classes for the same
`nav-cart-contianer__icon--borderless`
`nav-cart-contianer__icon--bordered`

2022-05-18 08:07 UTC, pashedin commented on src/components/Navbar/Navbar.tsx
> +      <div className="nav-bar-profileDiv">
check the case please

2022-05-18 08:08 UTC, pashedin requested changes
all looks okay, please correct and check the casing for all, classes

2022-05-18 08:08 UTC, pashedin commented on src/components/Navbar/Navbar.tsx
> +                wishCarsCount === 0 ? "nav__icon--hide" : "nav__wishCount"
nice

2022-05-18 11:04 UTC, Pratishah commented
![image](https://user-images.githubusercontent.com/96569364/169024522-9e2b2f04-2c06-4f98-b572-16c86728102c.png)
![image](https://user-images.githubusercontent.com/96569364/169024611-9a97ee2f-11d4-4f0d-bcca-f93665e388a3.png)

2022-05-18 12:20 UTC, pashedin approved these changes

2022-05-18 12:20 UTC, merged